apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ziad-app.fullname" . }}
  labels:
    {{- include "ziad-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ziad-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ziad-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        env:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: python-app-realse-1-redis-master
        - name: ENVIRONMENT
          value: DEV
        - name: PORT
          value: "8000"
        - name: REDIS_DB
          value: "0"
        ports:
        - containerPort: 80
        command: ["sleep","infinity"]